# Generated by Django 4.2.4 on 2023-08-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_id', models.IntegerField(verbose_name='Numero da Conta')),
                ('saldo', models.FloatField(verbose_name='Saldo')),
            ],
        ),
    ]
